Licensed under the MIT License.

Copyright (c) 2021-2031. All rights reserved.

# Model Selection with AutoKeras

* It will try to find thr optimal neural network architecture & hyperparameters for you. 
* Totorials: https://autokeras.com/tutorial/overview/

In [39]:
import autokeras
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, balanced_accuracy_score

### Regression
* AutoKeras `StructuredDataRegressor`: https://autokeras.com/structured_data_regressor/
* Too slow when the dataset has either large dimensions or large number of records, so here removed many features

In [57]:
df = pd.read_pickle('../luigi_pipeline/output/preprocessed_data.pkl')
print(df.shape)

df.head()

(693861, 22)

,Store,Date,Year,Month,Quarter,Customers_larger_than_3000,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,...,Promo2SinceWeek,Promo2SinceYear,PromoInterval,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,2015-07-31,2015,7,941,0.0,2,0,1270.0,9,...,-1,-1,0,5,5263,555,1,1,0,1
1,1,2015-07-30,2015,7,940,0.0,2,0,1270.0,9,...,-1,-1,0,4,5020,546,1,1,0,1
2,1,2015-07-29,2015,7,939,0.0,2,0,1270.0,9,...,-1,-1,0,3,4782,523,1,1,0,1
3,1,2015-07-28,2015,7,938,0.0,2,0,1270.0,9,...,-1,-1,0,2,5011,560,1,1,0,1
4,1,2015-07-27,2015,7,937,0.0,2,0,1270.0,9,...,-1,-1,0,1,6102,612,1,1,0,1

In [58]:
cat_cols = [col for col in df.select_dtypes(include='category').columns if col != 'Year']
df.drop(cat_cols, axis=1, inplace=True)

df.head()

,Date,Year,Customers_larger_than_3000,CompetitionDistance,Sales,Customers
0,2015-07-31,2015,0.0,1270.0,5263,555
1,2015-07-30,2015,0.0,1270.0,5020,546
2,2015-07-29,2015,0.0,1270.0,4782,523
3,2015-07-28,2015,0.0,1270.0,5011,560
4,2015-07-27,2015,0.0,1270.0,6102,612

In [59]:
# train, test split for df
train_df = df.loc[df['Year'].astype(str) < '2015']
test_df = df.loc[df['Year'].astype(str) == '2015']

y_train, y_test = train_df['Sales'], test_df['Sales']
X_train, X_test = train_df.drop(['Sales', 'Date', 'Year'], axis=1), test_df.drop(['Sales', 'Date', 'Year'], axis=1)

X_train.reset_index(inplace=True, drop=True)
X_test.reset_index(inplace=True, drop=True)
y_train.reset_index(inplace=True, drop=True)
y_test.reset_index(inplace=True, drop=True)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
X_train.head()

(532529, 3) (161332, 3) (532529,) (161332,)

   Customers_larger_than_3000  CompetitionDistance  Customers
0                         0.0               1270.0        327
1                         0.0               1270.0        703
2                         0.0               1270.0        700
3                         0.0               1270.0          0
4                         0.0               1270.0        684

In [60]:
ak_regressor = autokeras.StructuredDataRegressor(max_trials=3, tuner='bayesian')
ak_regressor.fit(X_train, y_train, epochs=3)

Trial 3 Complete [00h 07m 41s]
val_loss: 7056720.0

Best val_loss So Far: 7056720.0
Total elapsed time: 00h 44m 37s
INFO:tensorflow:Oracle triggered exit
Epoch 1/3
16642/16642 [==============================] - 111s 7ms/step - loss: 9390212.0000 - mean_squared_error: 9390212.0000
Epoch 2/3
16642/16642 [==============================] - 120s 7ms/step - loss: 8155811.0000 - mean_squared_error: 8155811.0000
Epoch 3/3
16642/16642 [==============================] - 123s 7ms/step - loss: 7367745.5000 - mean_squared_error: 7367745.5000
INFO:tensorflow:Assets written to: .\structured_data_regressor\best_model\assets

In [61]:
y_pred_regression = ak_regressor.predict(X_test)
print(r2_score(y_test, y_pred_regression.flatten().astype(np.float)))

5042/5042 [==============================] - 14s 3ms/step
-0.2587499301929723

In [62]:
keras_export_regression = ak_regressor.export_model()
keras_export_regression.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 3)]               0
_________________________________________________________________
multi_category_encoding (Mul (None, 3)                 0
_________________________________________________________________
normalization (Normalization (None, 3)                 7
_________________________________________________________________
dense (Dense)                (None, 1024)              4096
_________________________________________________________________
re_lu (ReLU)                 (None, 1024)              0
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0
_________________________________________________________________
regression_head_1 (Dense)    (None, 1)                 1025
=================================================================
Total params: 5,128
Trainable params: 5,121
Non-trainable params: 7
_________________________________________________________________

### Classification
* AutoKeras `StructuredDataClassifier`: https://autokeras.com/structured_data_classifier/

In [10]:
df30 = pd.read_csv('../../crystal_ball/data_collector/structured_data/leaf.csv')

y30 = df30['species']
X30 = df30.drop('species', axis=1)

X_train30, X_test30, y_train30, y_test30 = train_test_split(X30, y30, test_size=0.2,
                                               random_state=10, shuffle=True, stratify=y30)

X_train30.reset_index(inplace=True, drop=True)
X_test30.reset_index(inplace=True, drop=True)
y_train30.reset_index(inplace=True, drop=True)
y_test30.reset_index(inplace=True, drop=True)

print(X_train30.shape, X_test30.shape, y_train30.shape, y_test30.shape)
print(y_train30.nunique(), y_test30.nunique())

(272, 15) (68, 15) (272,) (68,)
30 30

In [11]:
ak_classifier = autokeras.StructuredDataClassifier(max_trials=10)
ak_classifier.fit(X_train30, y_train30, epochs=100)

Trial 10 Complete [00h 00m 39s]
val_accuracy: 0.75

Best val_accuracy So Far: 0.9375
Total elapsed time: 00h 06m 38s
INFO:tensorflow:Oracle triggered exit
Epoch 1/100
9/9 [==============================] - 1s 8ms/step - loss: 3.4849 - accuracy: 0.0110
Epoch 2/100
9/9 [==============================] - 0s 8ms/step - loss: 3.3863 - accuracy: 0.0221
Epoch 3/100
9/9 [==============================] - 0s 12ms/step - loss: 3.3047 - accuracy: 0.0515
Epoch 4/100
9/9 [==============================] - 0s 12ms/step - loss: 3.2301 - accuracy: 0.0882
Epoch 5/100
9/9 [==============================] - 0s 12ms/step - loss: 3.1576 - accuracy: 0.1213
Epoch 6/100
9/9 [==============================] - 0s 11ms/step - loss: 3.0842 - accuracy: 0.1507
Epoch 7/100
9/9 [==============================] - 0s 12ms/step - loss: 3.0065 - accuracy: 0.1875
Epoch 8/100
9/9 [==============================] - 0s 12ms/step - loss: 2.9225 - accuracy: 0.2132
Epoch 9/100
9/9 [==============================] - 0s 8ms/step - loss: 2.8315 - accuracy: 0.2390
Epoch 10/100
9/9 [==============================] - 0s 10ms/step - loss: 2.7330 - accuracy: 0.2757
Epoch 11/100
9/9 [==============================] - 0s 11ms/step - loss: 2.6281 - accuracy: 0.2794
Epoch 12/100
9/9 [==============================] - 0s 12ms/step - loss: 2.5201 - accuracy: 0.2868
Epoch 13/100
9/9 [==============================] - 0s 11ms/step - loss: 2.4128 - accuracy: 0.3125
Epoch 14/100
9/9 [==============================] - 0s 12ms/step - loss: 2.3092 - accuracy: 0.3382
Epoch 15/100
9/9 [==============================] - 0s 13ms/step - loss: 2.2116 - accuracy: 0.3676
Epoch 16/100
9/9 [==============================] - 0s 12ms/step - loss: 2.1205 - accuracy: 0.3897
Epoch 17/100
9/9 [==============================] - 0s 13ms/step - loss: 2.0351 - accuracy: 0.4118
Epoch 18/100
9/9 [==============================] - 0s 9ms/step - loss: 1.9558 - accuracy: 0.4338
Epoch 19/100
9/9 [==============================] - 0s 8ms/step - loss: 1.8811 - accuracy: 0.4669
Epoch 20/100
9/9 [==============================] - 0s 9ms/step - loss: 1.8104 - accuracy: 0.4853
Epoch 21/100
9/9 [==============================] - 0s 9ms/step - loss: 1.7433 - accuracy: 0.5000
Epoch 22/100
9/9 [==============================] - 0s 13ms/step - loss: 1.6799 - accuracy: 0.5257
Epoch 23/100
9/9 [==============================] - 0s 12ms/step - loss: 1.6204 - accuracy: 0.5588
Epoch 24/100
9/9 [==============================] - 0s 12ms/step - loss: 1.5641 - accuracy: 0.5809
Epoch 25/100
9/9 [==============================] - 0s 12ms/step - loss: 1.5108 - accuracy: 0.5993
Epoch 26/100
9/9 [==============================] - 0s 10ms/step - loss: 1.4604 - accuracy: 0.6250
Epoch 27/100
9/9 [==============================] - 0s 11ms/step - loss: 1.4128 - accuracy: 0.6397
Epoch 28/100
9/9 [==============================] - 0s 11ms/step - loss: 1.3679 - accuracy: 0.6581
Epoch 29/100
9/9 [==============================] - 0s 12ms/step - loss: 1.3250 - accuracy: 0.6691
Epoch 30/100
9/9 [==============================] - 0s 11ms/step - loss: 1.2845 - accuracy: 0.6875
Epoch 31/100
9/9 [==============================] - 0s 12ms/step - loss: 1.2463 - accuracy: 0.7022
Epoch 32/100
9/9 [==============================] - 0s 8ms/step - loss: 1.2100 - accuracy: 0.7132
Epoch 33/100
9/9 [==============================] - 0s 11ms/step - loss: 1.1756 - accuracy: 0.7279
Epoch 34/100
9/9 [==============================] - 0s 10ms/step - loss: 1.1431 - accuracy: 0.7463
Epoch 35/100
9/9 [==============================] - 0s 12ms/step - loss: 1.1122 - accuracy: 0.7500
Epoch 36/100
9/9 [==============================] - 0s 10ms/step - loss: 1.0826 - accuracy: 0.7574
Epoch 37/100
9/9 [==============================] - 0s 10ms/step - loss: 1.0547 - accuracy: 0.7610
Epoch 38/100
9/9 [==============================] - 0s 12ms/step - loss: 1.0282 - accuracy: 0.7647
Epoch 39/100
9/9 [==============================] - 0s 12ms/step - loss: 1.0028 - accuracy: 0.7684
Epoch 40/100
9/9 [==============================] - 0s 10ms/step - loss: 0.9785 - accuracy: 0.7831
Epoch 41/100
9/9 [==============================] - 0s 12ms/step - loss: 0.9550 - accuracy: 0.7941
Epoch 42/100
9/9 [==============================] - 0s 9ms/step - loss: 0.9326 - accuracy: 0.8015
Epoch 43/100
9/9 [==============================] - 0s 9ms/step - loss: 0.9113 - accuracy: 0.7978
Epoch 44/100
9/9 [==============================] - 0s 8ms/step - loss: 0.8910 - accuracy: 0.8015
Epoch 45/100
9/9 [==============================] - 0s 12ms/step - loss: 0.8714 - accuracy: 0.8051
Epoch 46/100
9/9 [==============================] - 0s 12ms/step - loss: 0.8528 - accuracy: 0.8051
Epoch 47/100
9/9 [==============================] - 0s 9ms/step - loss: 0.8349 - accuracy: 0.8162
Epoch 48/100
9/9 [==============================] - 0s 10ms/step - loss: 0.8177 - accuracy: 0.8199
Epoch 49/100
9/9 [==============================] - 0s 12ms/step - loss: 0.8010 - accuracy: 0.8235
Epoch 50/100
9/9 [==============================] - 0s 12ms/step - loss: 0.7849 - accuracy: 0.8272
Epoch 51/100
9/9 [==============================] - 0s 12ms/step - loss: 0.7695 - accuracy: 0.8309
Epoch 52/100
9/9 [==============================] - 0s 12ms/step - loss: 0.7546 - accuracy: 0.8309
Epoch 53/100
9/9 [==============================] - 0s 11ms/step - loss: 0.7403 - accuracy: 0.8382
Epoch 54/100
9/9 [==============================] - 0s 11ms/step - loss: 0.7265 - accuracy: 0.8382
Epoch 55/100
9/9 [==============================] - 0s 12ms/step - loss: 0.7133 - accuracy: 0.8382
Epoch 56/100
9/9 [==============================] - 0s 11ms/step - loss: 0.7004 - accuracy: 0.8382
Epoch 57/100
9/9 [==============================] - 0s 12ms/step - loss: 0.6881 - accuracy: 0.8382
Epoch 58/100
9/9 [==============================] - 0s 9ms/step - loss: 0.6760 - accuracy: 0.8419
Epoch 59/100
9/9 [==============================] - 0s 13ms/step - loss: 0.6645 - accuracy: 0.8419
Epoch 60/100
9/9 [==============================] - 0s 12ms/step - loss: 0.6534 - accuracy: 0.8456
Epoch 61/100
9/9 [==============================] - 0s 9ms/step - loss: 0.6424 - accuracy: 0.8493
Epoch 62/100
9/9 [==============================] - 0s 11ms/step - loss: 0.6316 - accuracy: 0.8493
Epoch 63/100
9/9 [==============================] - 0s 12ms/step - loss: 0.6214 - accuracy: 0.8529
Epoch 64/100
9/9 [==============================] - 0s 12ms/step - loss: 0.6115 - accuracy: 0.8529
Epoch 65/100
9/9 [==============================] - 0s 12ms/step - loss: 0.6019 - accuracy: 0.8529
Epoch 66/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5926 - accuracy: 0.8566
Epoch 67/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5835 - accuracy: 0.8566
Epoch 68/100
9/9 [==============================] - 0s 13ms/step - loss: 0.5746 - accuracy: 0.8640
Epoch 69/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5659 - accuracy: 0.8713
Epoch 70/100
9/9 [==============================] - 0s 13ms/step - loss: 0.5576 - accuracy: 0.8713
Epoch 71/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5495 - accuracy: 0.8713
Epoch 72/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5414 - accuracy: 0.8713
Epoch 73/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5336 - accuracy: 0.8750
Epoch 74/100
9/9 [==============================] - 0s 10ms/step - loss: 0.5259 - accuracy: 0.8787
Epoch 75/100
9/9 [==============================] - 0s 11ms/step - loss: 0.5184 - accuracy: 0.8787
Epoch 76/100
9/9 [==============================] - 0s 12ms/step - loss: 0.5111 - accuracy: 0.8787
Epoch 77/100
9/9 [==============================] - 0s 8ms/step - loss: 0.5040 - accuracy: 0.8860
Epoch 78/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4970 - accuracy: 0.8897
Epoch 79/100
9/9 [==============================] - 0s 10ms/step - loss: 0.4901 - accuracy: 0.8897
Epoch 80/100
9/9 [==============================] - 0s 11ms/step - loss: 0.4834 - accuracy: 0.8897
Epoch 81/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4770 - accuracy: 0.8897
Epoch 82/100
9/9 [==============================] - 0s 11ms/step - loss: 0.4707 - accuracy: 0.8897
Epoch 83/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4645 - accuracy: 0.8897
Epoch 84/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4586 - accuracy: 0.8934
Epoch 85/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4528 - accuracy: 0.8934
Epoch 86/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4471 - accuracy: 0.8934
Epoch 87/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4415 - accuracy: 0.8934
Epoch 88/100
9/9 [==============================] - 0s 9ms/step - loss: 0.4359 - accuracy: 0.8934
Epoch 89/100
9/9 [==============================] - 0s 9ms/step - loss: 0.4305 - accuracy: 0.8934
Epoch 90/100
9/9 [==============================] - 0s 9ms/step - loss: 0.4251 - accuracy: 0.8934
Epoch 91/100
9/9 [==============================] - 0s 9ms/step - loss: 0.4199 - accuracy: 0.8971
Epoch 92/100
9/9 [==============================] - 0s 9ms/step - loss: 0.4149 - accuracy: 0.8971
Epoch 93/100
9/9 [==============================] - 0s 12ms/step - loss: 0.4099 - accuracy: 0.9007
Epoch 94/100
9/9 [==============================] - 0s 13ms/step - loss: 0.4050 - accuracy: 0.8971
Epoch 95/100
9/9 [==============================] - 0s 11ms/step - loss: 0.4002 - accuracy: 0.8971
Epoch 96/100
9/9 [==============================] - 0s 8ms/step - loss: 0.3956 - accuracy: 0.8971
Epoch 97/100
9/9 [==============================] - 0s 8ms/step - loss: 0.3909 - accuracy: 0.9044
Epoch 98/100
9/9 [==============================] - 0s 12ms/step - loss: 0.3865 - accuracy: 0.9044
Epoch 99/100
9/9 [==============================] - 0s 9ms/step - loss: 0.3820 - accuracy: 0.9118
Epoch 100/100
9/9 [==============================] - 0s 9ms/step - loss: 0.3776 - accuracy: 0.9118
INFO:tensorflow:Assets written to: .\structured_data_classifier\best_model\assets

In [21]:
y_pred_classification = ak_classifier.predict(X_test30)
print(balanced_accuracy_score(y_test30, y_pred_classification.flatten().astype(np.float)))

3/3 [==============================] - 0s 6ms/step
0.8444444444444446

In [22]:
keras_export_classification = ak_classifier.export_model()
keras_export_classification.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 15)]              0
_________________________________________________________________
multi_category_encoding (Mul (None, 15)                0
_________________________________________________________________
normalization (Normalization (None, 15)                31
_________________________________________________________________
dense (Dense)                (None, 32)                512
_________________________________________________________________
re_lu (ReLU)                 (None, 32)                0
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056
_________________________________________________________________
re_lu_1 (ReLU)               (None, 32)                0
_________________________________________________________________
dense_2 (Dense)              (None, 30)                990
_________________________________________________________________
classification_head_1 (Softm (None, 30)                0
=================================================================
Total params: 2,589
Trainable params: 2,558
Non-trainable params: 31
_________________________________________________________________